using Health.UI;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Http;
using Radzen;
using SharedComponent.Server;
using SharedComponent.Server.Common;
using SharedComponent.Server.Constants;
using Toolbelt.Blazor.Extensions.DependencyInjection;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
//builder.Services.TryAddConfiguration<ApiSetting>(builder.Configuration);
//builder.Services.AddScoped(sp => new HttpClient {   BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)  }.EnableIntercept(sp));
builder.Services.AddApiServices(ApiPath.BaseUrl);
builder.Services.AddScoped<DialogService>();
builder.Services.AddScoped<NotificationService>();
builder.Services.AddScoped<TooltipService>();
builder.Services.AddScoped<ContextMenuService>();
builder.Services.RemoveAll<IHttpMessageHandlerBuilderFilter>();
await builder.Build().RunAsync();
